# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aO aX rI
.outputs aI rO rY
.graph
aI+ rI-
aI- p0
aO+ rO- p2 p3
aO- p4
aX+ rO+
aX- p5
rI+ aI+ rY+
rI- aI-
rO+ aO+
rO- aO-
rY+ rY- p1
rY- p6
p0 rI+
p1 aX+
p2 rY-
p3 aI+
p4 aI-
p5 aI-
p6 aX-
.marking {p0}
.end
