# STG file generated by Workcraft 3 (Return of the Hazard), version 3.1.9
.model Untitled
.inputs aC aF aG aT rA
.outputs aA rC rD rG
.graph
aA+ rA-
aA- p0
aC+ rC-
aC- p1
aF+ aA+
aF- aA-
aG+ rD+
aG- rD-
aT+ aT- p3
aT- rC+
rA+ p1
rA- aF- p3
rC+ aC+
rC- aC-
rD+ p2
rD- p4
rG+ aG+
rG- aG-
p0 rA+
p1 rG+
p2 aF+ aT+
p3 rG-
p4 aF- aT-
.marking {p0}
.end
